import { useState } from 'react';
import { Asset, AssetType, AssetStatus, ProductionScene, ProductionCharacter, ProductionLocation } from '../../../types/production';
import { Plus, Search, Pencil, Trash2, Image, FileVideo, Music, Link2, Sparkles } from 'lucide-react';

interface AssetLibraryProps {
  assets: Asset[];
  scenes: ProductionScene[];
  characters: ProductionCharacter[];
  locations: ProductionLocation[];
  onAddAsset: (asset: Omit<Asset, 'id' | 'dateCreated' | 'dateModified'>) => void;
  onUpdateAsset: (asset: Asset) => void;
  onDeleteAsset: (assetId: string) => void;
}

export default function AssetLibrary({
  assets,
  scenes,
  characters,
  locations,
  onAddAsset,
  onUpdateAsset,
  onDeleteAsset,
}: AssetLibraryProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [typeFilter, setTypeFilter] = useState<AssetType | null>(null);
  const [isAdding, setIsAdding] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);

  // Form state
  const [formName, setFormName] = useState('');
  const [formType, setFormType] = useState<AssetType>('placeholder');
  const [formDescription, setFormDescription] = useState('');
  const [formStatus, setFormStatus] = useState<AssetStatus>('pending');
  const [formSceneId, setFormSceneId] = useState('');
  const [formCharacterId, setFormCharacterId] = useState('');
  const [formLocationId, setFormLocationId] = useState('');
  const [formNotes, setFormNotes] = useState('');

  const filteredAssets = assets.filter((asset) => {
    const matchesSearch =
      asset.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      asset.description.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesType = !typeFilter || asset.type === typeFilter;
    return matchesSearch && matchesType;
  });

  const startAdding = () => {
    setFormName('');
    setFormType('placeholder');
    setFormDescription('');
    setFormStatus('pending');
    setFormSceneId('');
    setFormCharacterId('');
    setFormLocationId('');
    setFormNotes('');
    setIsAdding(true);
  };

  const handleSave = () => {
    if (!formName.trim()) return;
    onAddAsset({
      name: formName,
      type: formType,
      description: formDescription,
      status: formStatus,
      sceneId: formSceneId || undefined,
      characterId: formCharacterId || undefined,
      locationId: formLocationId || undefined,
      notes: formNotes,
    });
    setIsAdding(false);
  };

  const handleDelete = (assetId: string) => {
    if (deleteConfirm === assetId) {
      onDeleteAsset(assetId);
      setDeleteConfirm(null);
    } else {
      setDeleteConfirm(assetId);
    }
  };

  const typeConfig: Record<AssetType, { label: string; icon: React.ComponentType<{ className?: string }>; color: string }> = {
    image: { label: 'Image', icon: Image, color: 'bg-blue-500/10 text-blue-400 border-blue-500/20' },
    video: { label: 'Video', icon: FileVideo, color: 'bg-purple-500/10 text-purple-400 border-purple-500/20' },
    audio: { label: 'Audio', icon: Music, color: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' },
    reference: { label: 'Reference', icon: Link2, color: 'bg-amber-500/10 text-amber-400 border-amber-500/20' },
    placeholder: { label: 'Placeholder', icon: Sparkles, color: 'bg-gray-500/10 text-gray-400 border-gray-500/20' },
  };

  const statusColors: Record<AssetStatus, string> = {
    pending: 'bg-gray-500/10 text-gray-400 border-gray-500/20',
    generating: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    complete: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    failed: 'bg-red-500/10 text-red-400 border-red-500/20',
  };

  return (
    <div>
      {/* Info Banner */}
      <div className="bg-[#1a1b2e] border border-indigo-500/20 rounded-xl p-4 mb-4 flex items-start gap-3">
        <Sparkles className="w-5 h-5 text-indigo-400 shrink-0 mt-0.5" />
        <div>
          <h3 className="text-sm font-semibold text-gray-200 mb-1">Asset Pipeline (Coming Soon)</h3>
          <p className="text-xs text-gray-400 leading-relaxed">
            Assets will be generated by AI systems in future stages. For now, use this panel to plan and track which assets you'll need for each scene, character, and location.
          </p>
        </div>
      </div>

      {/* Toolbar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3 mb-4">
        <div className="relative flex-1 w-full">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500" />
          <input
            type="text"
            placeholder="Search assets..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-3 py-2 bg-[#1a1b2e] border border-[#2a2b3d] rounded-lg text-sm text-gray-300 placeholder-gray-600 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/30 transition-colors"
          />
        </div>
        <button
          onClick={startAdding}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium rounded-lg transition-colors whitespace-nowrap"
          aria-label="Add new asset"
        >
          <Plus className="w-4 h-4" />
          Add Asset
        </button>
      </div>

      {/* Type Filter */}
      <div className="flex items-center gap-2 mb-4 flex-wrap">
        <span className="text-xs text-gray-500">Type:</span>
        <button
          onClick={() => setTypeFilter(null)}
          className={`px-2.5 py-1 text-xs rounded-full border transition-colors ${
            !typeFilter ? 'bg-indigo-600/20 text-indigo-300 border-indigo-500/30' : 'bg-[#1a1b2e] text-gray-400 border-[#2a2b3d] hover:border-gray-500'
          }`}
        >
          All
        </button>
        {(Object.keys(typeConfig) as AssetType[]).map((type) => {
          const config = typeConfig[type];
          return (
            <button
              key={type}
              onClick={() => setTypeFilter(typeFilter === type ? null : type)}
              className={`flex items-center gap-1 px-2.5 py-1 text-xs rounded-full border transition-colors ${
                typeFilter === type ? config.color : 'bg-[#1a1b2e] text-gray-400 border-[#2a2b3d] hover:border-gray-500'
              }`}
            >
              <config.icon className="w-3 h-3" />
              {config.label}
            </button>
          );
        })}
      </div>

      {/* Add Form */}
      {isAdding && (
        <div className="bg-[#1a1b2e] border border-indigo-500/30 rounded-xl p-5 mb-4">
          <h3 className="text-sm font-semibold text-white mb-4">New Asset</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <input
              type="text"
              placeholder="Asset name..."
              value={formName}
              onChange={(e) => setFormName(e.target.value)}
              className="px-3 py-2 bg-[#12132a] border border-[#2a2b3d] rounded-lg text-sm text-gray-200 placeholder-gray-600 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/30 transition-colors"
              aria-label="Asset name"
            />
            <select
              value={formType}
              onChange={(e) => setFormType(e.target.value as AssetType)}
              className="px-3 py-2 bg-[#12132a] border border-[#2a2b3d] rounded-lg text-sm text-gray-200 focus:outline-none focus:border-indigo-500 transition-colors"
              aria-label="Asset type"
            >
              <option value="placeholder">Placeholder</option>
              <option value="reference">Reference</option>
              <option value="image">Image</option>
              <option value="video">Video</option>
              <option value="audio">Audio</option>
            </select>
            <select
              value={formSceneId}
              onChange={(e) => setFormSceneId(e.target.value)}
              className="px-3 py-2 bg-[#12132a] border border-[#2a2b3d] rounded-lg text-sm text-gray-200 focus:outline-none focus:border-indigo-500 transition-colors"
              aria-label="Link to scene"
            >
              <option value="">Link to scene (optional)...</option>
              {scenes.map((s) => (
                <option key={s.id} value={s.id}>{s.title}</option>
              ))}
            </select>
            <select
              value={formCharacterId}
              onChange={(e) => setFormCharacterId(e.target.value)}
              className="px-3 py-2 bg-[#12132a] border border-[#2a2b3d] rounded-lg text-sm text-gray-200 focus:outline-none focus:border-indigo-500 transition-colors"
              aria-label="Link to character"
            >
              <option value="">Link to character (optional)...</option>
              {characters.map((c) => (
                <option key={c.id} value={c.id}>{c.name}</option>
              ))}
            </select>
            <select
              value={formLocationId}
              onChange={(e) => setFormLocationId(e.target.value)}
              className="px-3 py-2 bg-[#12132a] border border-[#2a2b3d] rounded-lg text-sm text-gray-200 focus:outline-none focus:border-indigo-500 transition-colors"
              aria-label="Link to location"
            >
              <option value="">Link to location (optional)...</option>
              {locations.map((l) => (
                <option key={l.id} value={l.id}>{l.name}</option>
              ))}
            </select>
            <select
              value={formStatus}
              onChange={(e) => setFormStatus(e.target.value as AssetStatus)}
              className="px-3 py-2 bg-[#12132a] border border-[#2a2b3d] rounded-lg text-sm text-gray-200 focus:outline-none focus:border-indigo-500 transition-colors"
              aria-label="Status"
            >
              <option value="pending">Pending</option>
              <option value="generating">Generating</option>
              <option value="complete">Complete</option>
              <option value="failed">Failed</option>
            </select>
          </div>
          <textarea
            placeholder="Description..."
            value={formDescription}
            onChange={(e) => setFormDescription(e.target.value)}
            rows={2}
            className="w-full mt-3 px-3 py-2 bg-[#12132a] border border-[#2a2b3d] rounded-lg text-sm text-gray-200 placeholder-gray-600 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/30 transition-colors resize-y"
            aria-label="Description"
          />
          <textarea
            placeholder="Notes..."
            value={formNotes}
            onChange={(e) => setFormNotes(e.target.value)}
            rows={2}
            className="w-full mt-3 px-3 py-2 bg-[#12132a] border border-[#2a2b3d] rounded-lg text-sm text-gray-200 placeholder-gray-600 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/30 transition-colors resize-y"
            aria-label="Notes"
          />
          <div className="flex items-center gap-2 mt-4">
            <button
              onClick={handleSave}
              disabled={!formName.trim()}
              className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 disabled:bg-gray-700 disabled:text-gray-500 text-white text-sm font-medium rounded-lg transition-colors"
            >
              Add Asset
            </button>
            <button
              onClick={() => setIsAdding(false)}
              className="px-4 py-2 bg-[#22234a] hover:bg-[#2a2b3d] text-gray-300 text-sm font-medium rounded-lg border border-[#2a2b3d] transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Assets Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredAssets.length === 0 ? (
          <div className="col-span-full text-center py-12 bg-[#1a1b2e] border border-[#2a2b3d] rounded-xl">
            <Image className="w-10 h-10 text-gray-600 mx-auto mb-3" />
            <p className="text-sm text-gray-400">
              {searchQuery || typeFilter ? 'No assets match your filters.' : 'No assets yet.'}
            </p>
          </div>
        ) : (
          filteredAssets.map((asset) => {
            const typeConf = typeConfig[asset.type];
            const TypeIcon = typeConf.icon;
            const linkedScene = scenes.find((s) => s.id === asset.sceneId);
            const linkedCharacter = characters.find((c) => c.id === asset.characterId);
            const linkedLocation = locations.find((l) => l.id === asset.locationId);

            return (
              <div
                key={asset.id}
                className="bg-[#1a1b2e] border border-[#2a2b3d] rounded-xl overflow-hidden hover:border-[#3a3b5d] transition-colors"
              >
                {/* Asset Thumbnail */}
                <div className="aspect-video bg-gradient-to-br from-[#22234a] to-[#1a1b2e] flex items-center justify-center relative">
                  <TypeIcon className="w-8 h-8 text-gray-600" />
                  <div className={`absolute top-2 right-2 px-2 py-0.5 rounded text-[10px] font-medium ${statusColors[asset.status]}`}>
                    {asset.status}
                  </div>
                </div>

                {/* Asset Info */}
                <div className="p-3">
                  <div className="flex items-center gap-2 mb-1.5">
                    <span className={`flex items-center gap-1 px-1.5 py-0.5 text-[10px] font-medium rounded-full border ${typeConf.color}`}>
                      <TypeIcon className="w-3 h-3" />
                      {typeConf.label}
                    </span>
                  </div>
                  <h3 className="text-sm font-semibold text-gray-200">{asset.name}</h3>
                  {asset.description && (
                    <p className="text-xs text-gray-400 mt-1 line-clamp-2">{asset.description}</p>
                  )}
                  <div className="flex flex-wrap gap-1.5 mt-2">
                    {linkedScene && (
                      <span className="px-1.5 py-0.5 text-[10px] bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 rounded">
                        🎬 {linkedScene.title}
                      </span>
                    )}
                    {linkedCharacter && (
                      <span className="px-1.5 py-0.5 text-[10px] bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 rounded">
                        👤 {linkedCharacter.name}
                      </span>
                    )}
                    {linkedLocation && (
                      <span className="px-1.5 py-0.5 text-[10px] bg-amber-500/10 text-amber-400 border border-amber-500/20 rounded">
                        📍 {linkedLocation.name}
                      </span>
                    )}
                  </div>
                  <div className="flex items-center gap-1 mt-3 pt-3 border-t border-[#2a2b3d]">
                    <button
                      onClick={() => handleDelete(asset.id)}
                      className={`flex-1 flex items-center justify-center gap-1.5 px-3 py-1.5 text-xs rounded-lg transition-colors ${
                        deleteConfirm === asset.id
                          ? 'text-red-400 bg-red-500/10'
                          : 'text-gray-400 hover:text-red-400 hover:bg-[#22234a]'
                      }`}
                      aria-label={deleteConfirm === asset.id ? `Confirm delete ${asset.name}` : `Delete ${asset.name}`}
                    >
                      <Trash2 className="w-3 h-3" />
                      {deleteConfirm === asset.id ? 'Confirm' : 'Delete'}
                    </button>
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
