/**
 * Media Artifact Types — Chronos Studio Stage 8
 *
 * This domain manages actual media files and their metadata.
 * It bridges the gap between pipeline outputs and production assets.
 *
 * Architecture:
 *   GenerationOutput → MediaArtifact → AssetVersion → Asset
 *
 * Media artifacts represent actual files (or references to files).
 * Assets represent logical media items with versions and usage tracking.
 */

import { MediaType, MediaOutput } from './pipeline';
import { GenerationSource } from './ai';

// ─── Artifact Status ─────────────────────────────────────────────────────────

export type ArtifactStatus =
  | 'pending'      // Created but not yet stored
  | 'processing'   // Being processed/validated
  | 'ready'        // Available for use
  | 'failed'       // Processing failed
  | 'deleted';     // Marked for deletion

// ─── Storage Reference ───────────────────────────────────────────────────────

/**
 * Abstract storage reference.
 * The system doesn't know or care where files are actually stored.
 */
export interface StorageReference {
  /** Storage provider type */
  provider: 'local' | 'memory' | 'filesystem' | 's3' | 'url';

  /** Provider-specific path or identifier */
  path: string;

  /** Optional URL for direct access (if applicable) */
  url?: string;

  /** File size in bytes */
  size: number;

  /** Content hash for integrity/deduplication */
  checksum: string;
}

// ─── Media Artifact ──────────────────────────────────────────────────────────

/**
 * A media artifact represents an actual file or media resource.
 * Artifacts are created by the pipeline and consumed by assets.
 */
export interface MediaArtifact {
  id: string;
  projectId: string;

  /** Media type */
  type: MediaType;

  /** Original filename (if applicable) */
  filename: string;

  /** MIME type */
  mimeType: string;

  /** Storage reference */
  storage: StorageReference;

  /** Media-specific metadata */
  metadata: {
    /** Image/video dimensions */
    width?: number;
    height?: number;

    /** Audio/video duration in seconds */
    duration?: number;

    /** Video FPS */
    fps?: number;

    /** Audio sample rate */
    sampleRate?: number;

    /** Format/codec */
    format: string;

    /** Additional format-specific metadata */
    extra?: Record<string, any>;
  };

  /** Preview/thumbnail reference (for images/video) */
  preview?: StorageReference;

  /** Current status */
  status: ArtifactStatus;

  /** Generation source (if generated by pipeline) */
  generationSource?: {
    outputId: string;
    taskId: string;
    requestId: string;
  };

  /** Creation timestamp */
  createdAt: string;

  /** Last update */
  updatedAt: string;

  /** Error message if failed */
  error?: string;
}

// ─── Asset Version ───────────────────────────────────────────────────────────

/**
 * A version of an asset.
 * Assets can have multiple versions from iterative generation.
 */
export interface AssetVersion {
  id: string;
  assetId: string;

  /** Version number (1, 2, 3, ...) */
  versionNumber: number;

  /** The artifact for this version */
  artifactId: string;

  /** Generation provenance */
  provenance: {
    outputId: string;
    taskId: string;
    requestId: string;
    sourceType: GenerationSource['kind'];
    sourceId: string;
    contextSnapshot: string;
    promptHash: string;
  };

  /** Whether this is the current/active version */
  isCurrent: boolean;

  /** Creation timestamp */
  createdAt: string;

  /** User notes for this version */
  notes?: string;
}

// ─── Asset Origin ────────────────────────────────────────────────────────────

export type AssetOrigin =
  | 'generated'      // Created by AI generation pipeline
  | 'imported'       // Imported from external source
  | 'manual'         // Manually created/placeholder
  | 'reference';     // Reference image/media

// ─── Media Asset ─────────────────────────────────────────────────────────────

/**
 * A media asset represents a logical media item with versions and usage.
 * Assets are owned by Production and reference artifacts from the Media domain.
 */
export interface MediaAsset {
  id: string;
  projectId: string;

  /** Asset name */
  name: string;

  /** Media type */
  type: MediaType;

  /** How this asset was created */
  origin: AssetOrigin;

  /** Description */
  description: string;

  /** Current version ID */
  currentVersionId: string | null;

  /** All version IDs */
  versionIds: string[];

  /** Usage tracking */
  usage: {
    /** Characters using this asset */
    characterIds: string[];

    /** Locations using this asset */
    locationIds: string[];

    /** Scenes using this asset */
    sceneIds: string[];

    /** Shots using this asset */
    shotIds: string[];
  };

  /** Tags for organization */
  tags: string[];

  /** User notes */
  notes: string;

  /** Creation timestamp */
  createdAt: string;

  /** Last update */
  updatedAt: string;
}

// ─── Media Data ──────────────────────────────────────────────────────────────

/**
 * Complete media domain state for a project.
 */
export interface MediaData {
  artifacts: MediaArtifact[];
  assets: MediaAsset[];
  versions: AssetVersion[];
  lastSaved: string;
}

// ─── Storage Interface ───────────────────────────────────────────────────────

/**
 * Storage provider interface.
 * Abstracts file storage operations.
 */
export interface IMediaStorage {
  /**
   * Store an artifact.
   * Returns a storage reference.
   */
  store(
    projectId: string,
    type: MediaType,
    data: ArrayBuffer | Blob,
    filename: string
  ): Promise<StorageReference>;

  /**
   * Retrieve an artifact.
   */
  retrieve(ref: StorageReference): Promise<ArrayBuffer | null>;

  /**
   * Delete an artifact.
   */
  delete(ref: StorageReference): Promise<boolean>;

  /**
   * Check if artifact exists.
   */
  exists(ref: StorageReference): Promise<boolean>;

  /**
   * Generate a preview/thumbnail.
   */
  generatePreview?(ref: StorageReference): Promise<StorageReference | null>;
}
